name: veripol
description: A new Flutter project.

publish_to: "none"

version: 2.0.0+2

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  cloud_firestore: 4.13.0
  cupertino_icons: 1.0.2
  dropdown_button2: 2.3.6
  firebase_auth: 4.14.0
  firebase_core: 2.22.0
  flutter:
    sdk: flutter
  flutter_hooks: 0.20.5
  flutter_launcher_icons: 0.13.1
  flutter_svg: 2.0.7
  go_router: 12.1.1
  google_fonts: 5.1.0
  google_sign_in: 6.1.4
  provider: 6.0.2
  shared_preferences: 2.0.13
  syncfusion_flutter_charts: 22.1.39
  url_launcher: 6.0.20
  uuid: 3.0.6

dev_dependencies:
  flutter_lints: 2.0.2
  flutter_test:
    sdk: flutter
flutter_icons:
  android: "veripol_launcher_icon"
  image_path: "assets/icons/VeriPol_logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/data/locations.json
    - assets/data/candidates/

  fonts:
    - family: MountainScript
      fonts:
        - asset: assets/fonts/Mountain Script.ttf
