name: veripol
description: A new Flutter project.

publish_to: "none"

version: 2.0.0+2

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  cloud_firestore: 5.4.1
  cupertino_icons: 1.0.8
  dropdown_button2: 2.3.9
  firebase_auth: 5.2.1
  firebase_core: 3.4.1
  flutter:
    sdk: flutter
  flutter_hooks: 0.20.5
  flutter_launcher_icons: 0.13.1
  flutter_svg: 2.0.10+1
  go_router: 14.2.7
  google_fonts: 6.2.1
  google_sign_in: 6.2.1
  provider: 6.1.2
  shared_preferences: 2.3.2
  syncfusion_flutter_charts: 22.1.39
  url_launcher: 6.0.20
  uuid: 4.5.0

dev_dependencies:
  flutter_lints: 4.0.0
  flutter_test:
    sdk: flutter
flutter_icons:
  android: "veripol_launcher_icon"
  image_path: "assets/icons/VeriPol_logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/data/locations.json
    - assets/data/candidates/

  fonts:
    - family: MountainScript
      fonts:
        - asset: assets/fonts/Mountain Script.ttf
